### ISSUE TITLE
error: -march=: ISA string must begin with rv32 or rv64

### ISSUE THREAD

**Issue by sayanee** [esp-rs/esp-idf-sys#250]
I'm a beginner in Rust embedded. I'm trying to `cargo build` a [simple blinky program on ESP32-C3](https://github.com/shanemmattner/ESP32-C3_Rust_Tutorials/blob/main/Tutorials/p0-output/src/main.rs) (Thanks to Shane Mattner).

## Pre-requisites

I'm on macOS 12.7 with Python `3.12.0`.

I used [esp-idf-template](https://github.com/esp-rs/esp-idf-template#prerequisites) to generate the initial boilerplate with these options:

- Project Name: blinky
- Which MCU to target? ›esp32c3
- Configure advanced template options? ›false 

```
👨 ››› ~/Desktop
$ cargo generate esp-rs/esp-idf-template cargo
⚠️   Favorite `esp-rs/esp-idf-template` not found in config, using it as a git repository: https://github.com/esp-rs/esp-idf-template.git
🤷   Project Name: blinky
🔧   Destination: /Users/sayanee/Desktop/blinky ...
🔧   project-name: blinky ...
🔧   Generating template ...
✔ 🤷   Which MCU to target? · esp32c3
✔ 🤷   Configure advanced template options? · false
🔧   Moving generated files into: `/Users/sayanee/Desktop/blinky`...
🔧   Initializing a fresh Git repository
✨   Done! New project created /Users/sayanee/Desktop/blinky
```

## Code 

<details>
<summary>The blinky code in `src/main.rs` </summary>

```rs
use esp_idf_hal::{delay::FreeRtos, gpio::PinDriver, peripherals::Peripherals};
use esp_idf_sys as _;
use esp_println::println;

fn main() {
    esp_idf_sys::link_patches();

    let peripherals = Peripherals::take().unwrap();
    let mut led_pin = PinDriver::output(peripherals.pins.gpio8).unwrap();

    loop {
        led_pin.set_low().unwrap();
        println!("LED ON");
        FreeRtos::delay_ms(1000);

        led_pin.set_high().unwrap();
        println!("LED OFF");
        FreeRtos::delay_ms(1000);
    }
}
```
</details>

## Config 

<details>
<summary>`Cargo.toml`</summary>

```toml
[package]
name = "blinky"
version = "0.1.0"
authors = ["Sayanee <sayanee@gmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.66"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
pio = ["esp-idf-sys/pio"]

[dependencies]
esp-idf-sys = { version = "0.32", features = ["binstart"] }
esp-idf-hal = "0.40"
esp-println = { version = "0.3.1", features = ["esp32c3"] }

[build-dependencies]
embuild = "0.30.4"
```
</details>

<details> 
<summary>And `.cargo/config.toml` has:</summary>

```toml
[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash --monitor"
rustflags = ["-C", "default-linker-libraries"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
ESP_IDF_VERSION = "v4.4.6"
```
</details>

## Error

<details>
<summary>My error when I run `cargo build`:</summary>

```
/Users/sayanee/Desktop/blinky/.embuild/espressif/tools/riscv32-esp-elf/esp-2021r2-patch5-8.4.0/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/bin/ld: -march=: ISA string must begin with rv32 or rv64
/Users/sayanee/Desktop/blinky/.embuild/espressif/tools/riscv32-esp-elf/esp-2021r2-patch5-8.4.0/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/bin/ld: failed to merge target specific data of file /Users/sayanee/Desktop/blinky/.embuild/espressif/tools/riscv32-esp-elf/esp-2021r2-patch5-8.4.0/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/lib/rv32imc/ilp32/no-rtti/libc.a(lib_a-atexit.o)
/Users/sayanee/Desktop/blinky/.embuild/espressif/tools/riscv32-esp-elf/esp-2021r2-patch5-8.4.0/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/bin/ld: -march=: ISA string must begin with rv32 or rv64
/Users/sayanee/Desktop/blinky/.embuild/espressif/tools/riscv32-esp-elf/esp-2021r2-patch5-8.4.0/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/bin/ld: failed to merge target specific data of file /Users/sayanee/Desktop/blinky/.embuild/espressif/tools/riscv32-esp-elf/esp-2021r2-patch5-8.4.0/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/lib/rv32imc/ilp32/no-rtti/libc.a(lib_a-__atexit.o)
          collect2: error: ld returned 1 exit status


          Stack backtrace:
             0: anyhow::backtrace::capture::Backtrace::capture
             1: anyhow::error::<impl anyhow::Error>::msg
             2: ldproxy::main
             3: std::sys_common::backtrace::__rust_begin_short_backtrace
             4: std::rt::lang_start::{{closure}}
             5: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
                       at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:284:13
                std::panicking::try::do_call
                       at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
                std::panicking::try
                       at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
                std::panic::catch_unwind
                       at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
                std::rt::lang_start_internal::{{closure}}
                       at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:48
                std::panicking::try::do_call
                       at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
                std::panicking::try
                       at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
                std::panic::catch_unwind
                       at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
                std::rt::lang_start_internal
                       at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:20
             6: _main


error: could not compile `blinky` (bin "blinky") due to previous error
```
</details>

I'm really not sure what I am doing wrong. Apologies if this is not the right place to post this issue, but I thought the Rust lang forum would be too generic for this error.
